imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    translator:      ~
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: %kernel.debug%
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig', 'php'] } #assets_version: SomeVersionScheme
    default_locale:  %locale%
    trust_proxy_headers: false # Should Request object should trust proxy headers (X_FORWARDED_FOR/HTTP_CLIENT_IP)
    session:         ~

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    bundles:        ['CorujaPlesyndBundle', 'CorujaTodoBundle']
    node:           /usr/bin/node
    filters:
        uglifyjs: ~
        uglifycss: ~

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        #auto_mapping: true
        entity_managers:
            default:
              connection: default
              mappings:
                CorujaPlesyndBundle:
                    type: annotation
                    dir: Entity
                    prefix: Coruja\PlesyndBundle\Entity\
                CorujaUserBundle:
                    type: annotation
                    dir: Entity
                    prefix: Coruja\UserBundle\Entity\
                CorujaTodoBundle:
                    type: annotation
                    dir: Entity
                    prefix: Coruja\TodoBundle\Entity\
                FOSUserBundle: ~

fos_rest:
    body_listener: true
    format_listener:
        default_priorities: ['json', html, '*/*']
        fallback_format: html
        prefer_extension: true
    view:
        view_response_listener: true
    routing_loader:
            default_format: json

fos_user:
    db_driver: orm
    firewall_name: main
    user_class: Coruja\UserBundle\Entity\User
    service:
            mailer: coruja.user.mailer
    registration:
        confirmation:
            from_email:
                address:        account@plesynd.de
                sender_name:    Plesynd Registration

sensio_framework_extra:
    # wegen FOSRestBundle ausgestellt https://github.com/FriendsOfSymfony/FOSRestBundle/blob/master/Resources/doc/3-listener-support.md
    view:    { annotations: false }
    router:  { annotations: true }

nelmio_api_doc: ~

nelmio_cors:
    paths:
        '^/(todo/api|login|logout)':
            allow_origin: ['http://127.0.0.1:8080', 'http://plesynd']
#            allow_origin: ['*']
            allow_headers: ['X-REQUESTED-WITH', 'Content-Type']
            allow_methods: ['POST', 'PUT', 'GET', 'DELETE', 'OPTIONS'],
            # Location Header is used for POST Request Answers (URI of created Item)
            expose_headers: ['Location']
            max_age: 3600
            allow_credentials: true

coruja_wookie_connector:
    protocol: http://
    host: localhost
    port: 8080
    path: wookie/
    api_key: TEST
    shared_data_key: shared_data
    login_name: user
    screen_name : ~

# Swiftmailer Configuration
swiftmailer:
    transport:  %mailer_transport%
    host:       %mailer_host%
    username:   %mailer_user%
    password:   %mailer_password%
    port:       %mailer_port%
    encryption: %mailer_encryption%
    auth_mode:  %mailer_auth_mode%
    delivery_address:  %delivery_address%
    disable_delivery: false
    spool: { type: memory }