parameters:
    database_driver:   pdo_mysql
    database_host:     localhost
    database_port:     ~
    database_name:     plesynd
    database_user:     root
    database_password: flirtme

    mailer_transport:  smtp
    mailer_host:       smtp.ipark-media.de
    mailer_user:       r.sachse@ipark-media.de
    mailer_password:   sarom
    mailer_encryption: null
    mailer_auth_mode:  plain
    mailer_port:       25
    delivery_address:  sarom@web.de

    locale:            en
    secret:            dFgtGhfkErfkgTkf12__39j
