parameters:
    database_driver:   pdo_mysql
    database_host:     localhost
    database_port:     ~
    database_name:     plesynd
    database_user:
    database_password:

    mailer_transport:  smtp
    mailer_host:
    mailer_user:
    mailer_password:
    mailer_encryption: null
    mailer_auth_mode:  plain
    mailer_port:       25
    delivery_address:

    locale:            en
    secret:
