#coruja_angular_module:
#    resource: "@CorujaAngularModuleBundle/Controller/"
#    type:     annotation
#    prefix:   /

CorujaWookieConnectorBundle:
    resource: "@CorujaWookieConnectorBundle/Controller/"
    type:     annotation
    prefix:   /

CorujaPlesyndBundle:
    resource: "@CorujaPlesyndBundle/Controller/"
    type:     annotation
    prefix:   /

CorujaTodoBundle:
    resource: "@CorujaTodoBundle/Controller/"
    type:     annotation
    prefix:   /

CorujaUserBundle:
    resource: "@CorujaUserBundle/Controller/"
    type:     annotation
    prefix:   /

logout:
    pattern:   /logout


#CorujaTodoBundle:
#    resource: "@CorujaTodoBundle/Resources/config/routing.yml"
#    prefix:   /

# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
