#coruja_angular_module:
#    resource: "@CorujaAngularModuleBundle/Controller/"
#    type:     annotation
#    prefix:   /

login_check:
    pattern:   /login_check

logout:
    pattern:   /logout

CorujaWookieConnectorBundle:
    resource: "@CorujaWookieConnectorBundle/Controller/"
    type:     annotation
    prefix:   /

CorujaPlesyndBundle:
    resource: "@CorujaPlesyndBundle/Controller/"
    type:     annotation
    prefix:   /

CorujaTodoBundle:
    resource: "@CorujaTodoBundle/Controller/"
    type:     annotation
    prefix:   /

CorujaUserBundle:
    resource: "@CorujaUserBundle/Controller/"
    type:     annotation
    prefix:   /

fos_user_registration_confirm:
    pattern:   "#/account_confirmation/{token}"


#CorujaTodoBundle:
#    resource: "@CorujaTodoBundle/Resources/config/routing.yml"
#    prefix:   /

# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
