CorujaTodoBundle_index:
    pattern:  /todo/
    defaults: { _controller: CorujaTodoBundle:TodoApp:index }

CorujaTodoBundle_appcache:
    pattern:  /todo/cache.appcache
    defaults: { _controller: CorujaTodoBundle:TodoApp:appcache }
